# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-12 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='token',
            name='account',
        ),
        migrations.RemoveField(
            model_name='token',
            name='host_user_bind',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
