# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-11 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='cmd',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='session',
        ),
    ]
