# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20180212_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=128, verbose_name='Token')),
                ('expire', models.IntegerField(default=300, verbose_name='超时时间(s)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Token 生成时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Account')),
                ('host_user_bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.HostUserBind')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('host_user_bind', 'val')]),
        ),
    ]
