# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-11 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20180211_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionlog',
            old_name='start_dat',
            new_name='start_date',
        ),
    ]
