# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_auto_20180215_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='同学姓名')),
                ('Amount_money', models.SmallIntegerField(verbose_name='金额')),
            ],
        ),
    ]
