# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
