# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-18 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_party_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日期'),
        ),
    ]
