# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_auto_20180218_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='type',
            field=models.CharField(default='[人民币] 元', max_length=25, verbose_name='种类'),
        ),
    ]
